### ISSUE TITLE
Warlock/Bard Multiclass Edge Case

### ISSUE THREAD

**Issue by asimone** [Rayuaz/spell-level-buttons-for-dnd5e#2]
![Screenshot 2021-07-15 172734](https://user-images.githubusercontent.com/575279/125865782-29935828-c292-4031-842a-b357b7b43176.png)

In 5e when you have a Multiclass Warlock with another caster, you get your Warlock level Pact Slots and your other caster slots on the side as normal. You can upcast your standard Caster slots using your Warlock Slots, but not the other way around.

The edge case here is I tried to cast sleep and the upcast option is only level 2, not 5 in the case and when I try to use level 2 spell slot I get (the expected) "there are no level spell slots error"

**Comment by asimone** [comment]
I _do_ dig the UI, though. Dropdown doesn't make sense in this context.

**Comment by Rayuaz** [comment]
It's not really an multiclass edge case, the script just didn't account for warlocks, sorry about that haha. It has been fixed in the lastest update, though. Thanks for the report.
